### PR TITLE
[Key Vault]Change keyvault to track2

### PR DESCRIPTION
**Pull request by Luyunmt**
TokenCache not included in GA azure.identity, but in preview. Upgrading based on preview version.
#### Project ClearClipboard and Core
  Only change TargetFrameworkVersion from 4.5.1 to 4.6.1
#### Project Library
1. KeyVaultClient splits into SecretClient and CertificateClient
2. Update track1 secret api from track1 to track2
3. Update track1 certificate api track1 to track2
4. Change TargetFrameworkVersion from 4.5.1 to 4.6.1
#### Project Explorer
1.  Change  track1 secret model from track1 to track2.
2.  Change  track1 certificate model from track1 to track2.
3.  Change using track1 Project Library api to track2.
4.  Some track1 key vault model splits into secret model and certificate model.  
5.  Change TargetFrameworkVersion from 4.5.1 to 4.6.1

### CODE REVIEW

**Comment by jongio** [comment]
This can be closed in favor of #43

**Comment by v-xuto** [comment]
@jongio We don't have permission to close this PR, please help close it. Thanks.

**Comment by jongio** [comment]
I don't either.  Will have to talk to KV team.

**Comment by jongio** [comment]
This PR can be closed.

**Comment by v-xuto** [comment]
@jongio Help find the corresponding person to close this PR. Thanks a lot.

**Pull request closed without merging**
